[rke2_cluster]
# First host becomes the control plane (server)
# Additional hosts become worker nodes (agents)

rke2-control-1 ansible_host=44.201.78.70 ansible_user=ubuntu ansible_ssh_private_key_file=~/github/ec2.pem
rke2-worker-1 ansible_host=13.219.101.191 ansible_user=ubuntu ansible_ssh_private_key_file=~/github/ec2.pem

[rke2_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
